# Generated by Django 5.1.7 on 2025-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='meta',
        ),
        migrations.AddField(
            model_name='graph',
            name='meta',
            field=models.JSONField(default='', verbose_name='Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graph',
            name='size',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FULL', 'Full')], default='NORMAL', max_length=31, verbose_name='Size'),
        ),
    ]
