# Generated by Django 5.1.7 on 2025-03-23 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='type',
            field=models.CharField(choices=[('LINE_CHART', 'Line Chart'), ('BAR_CHART', 'Bar Chart'), ('PIE_CHART', 'Pie Chart'), ('AREA_CHART', 'Area Chart'), ('RADAR_CHART', 'Radar Chart'), ('TABLE', 'Table')], default='LINE_CHART', max_length=31, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.graph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
