# Generated by Django 5.1.7 on 2025-03-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_datapoint_meta_graph_meta_alter_graph_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Meta'),
        ),
    ]
