# Generated by Django 5.1.7 on 2025-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_graph_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
